
services:
  clientserver:
    build: .
    ports:
      - 8000:8000
      - 5173:5173
    volumes:
     - /usr/src/app/node_modules
     - /usr/src/app/client/node_modules
     - /usr/src/app/server/node_modules
     - ./client:/usr/src/app/client
     - ./server:/usr/src/app/server
    environment:
     - PROXY_TARGET=127.0.0.1
     - PORT=8000
     - MONGO_HOST=db
     - NODE_ENV=development
    depends_on:
      - db
  db:
    build: ./db
    container_name: db
    ports:
      - 27017:27017



# services:
#   clientserver:
#     build: .
#     container_name: client_server
#     ports:
#      - "5713:5713"
#     #  - 8000:8000
#     stdin_open: true
#     tty: true
#     # volumes:
#     #  - ./client:/usr/src/app/client
#     #  - /usr/src/app/client/node_modules
#     #  - ./server:/usr/src/app/server
#     #  - /usr/src/app/server/node_modules
#     #  - /usr/src/app/node_modules
#     environment:
#       # - PROXY_TARGET=127.0.0.1
#       # - PORT=8000
#       - MONGO_HOST=db  # CAN'T BE 127.0.0.1 !!!!!
#       - NODE_ENV=development
#   #   depends_on:
#   #     - db


#   # db:
#   #   build: ./db
#   #   container_name: db
#   #   ports:
#   #    - 27017:27017
    